server:
  port: 8083

spring:
  application:
    name: order-service
  cloud:
    openfeign:
     circuitbreaker:
       enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      prefer-ip-address: true

order:
  defaultMessage: "Your order is being processed!"


resilience4j:
  circuitbreaker:
    instances:
      coffee-service:
        slidingWindowSize: 5
        minimumNumberOfCalls: 1
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents,refresh
  endpoint:
    circuitbreakers:
      enabled: true
    circuitbreakerevents:
      enabled: true



